### ISSUE TITLE
Shamans are pink, and they should probably be blue, espeically since pallies will be avail next week.

### ISSUE THREAD

**Issue by Scrybatog** [leatrix/leatrix-plus-classic#14]

**Comment by leatrix** [comment]
In original Burning Crusade, when both factions were given the ability to play both classes, shaman class color was changed from pink to blue in the pre-patch prior to launch.  Burning Crusade Classic will follow the same way.  Shaman class color will be changed from pink to blue in the pre-patch for characters progressing into Burning Crusade.

For Classic Era realms, since neither faction can play both classes, shaman class color is likely to remain pink.  Changing this to blue through addons cannot be done without causing problems (though addons that change the color do exist regardless of that) so won't be added to Leatrix Plus for World of Warcraft Classic.
