### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by SawyerMBlack** [leatrix/leatrix-plus-classic#30]
I'm not sure if you want these to be individual requests. This is the very first request I've ever done on github so I apologize.  

I'm going to be honest here, the features I'm requesting are already found in other addons, but the addons I'm referring to have lower update reliability than yours. If I want to continue seeing these features, I think they're better off being offered by your project.  

Here are the options requests:  
* Auto-track reputation when you enter a reputation zone (Hydraxian for MC, CC for AQ20, Brood for AQ40, etc) or if your reputation changes. For example if you get X reputation with Argent Dawn, your reputation bar automatically changes to Argent Dawn. (Addon: Reputation Watcher, currently causes errors)  

* Text is added behind reputation updates to show your current standing with that reputation, and the message is shortened. So "Your Argent Dawn reputation has increased by 10" would turn into "+10 Argent Dawn reputation (6491/21000)" (Addon: Reputable, currently causes errors)  

* Shamans text color is changed from pink to blue. (Addon: BlueShamans)  

* Take a snapshot of your bank so you can view it from anywhere (Addon: BankChecker)  

* Add the travel time to the Flight Menu with a countdown timer (Addon: InFlight)  

* Option to change portrait to class icon  

Also sorry I don't know how to add a "feedback" label to this.

**Comment by leatrix** [comment]
'Show flight times' has been added to the latest alpha releases of LTP for Classic Era/SoM and BCC.  If enabled, a flight time progress bar will be shown when you take a flight.  Note that for non-English locales, the progress bar will only show if the flight point names have been translated.

Changing portraits to class icons is bad for performance.  The default portrait texture is refreshed too often.  There are standalone addons that do this and they are all bad for performance.  It's a pity because class icon portraits would be a useful setting but I won't add anything to LTP that affects user performance.

Changing shaman class color can't be done without tainting the UI.  Again, there are standalone addons that do this and they all taint the UI which causes problems with the raid container frame.  I won't add anything to LTP that taints the UI no matter how useful it is.

You don't need to add labels to tickets.  I add a label to a ticket when I action it.

Other suggestions noted.  Hope you like the new flight times setting.  I love it.  It's a really nice addition to LTP Classic Era/SoM and BCC.  I appreciate your feedback.

**Comment by leatrix** [comment]
So flight time is included in the latest release for Classic and BCC.  I added a lot of flight times but some may be inaccurate or missing.  So if you enable the setting, flight times will be printed in chat when you land (for now at least).  If you notice that the flight time is wrong, report it to me and I will update the addon.  If people report inaccurate or missing flight times, the setting will work perfectly.  Also the setting currently uses translations for flight point names.  It's possible that could be changed in future (so translations aren't needed) but see how it goes.  I love the flight time setting but as Blizzard don't publish flight data anywhere, the times are all from player experience.  There's lots of flight data floating around the web but lots of it is inaccurate partly because it's taken from a different Wow game and partly because many addon authors have quit developing their addons.  But if people report then the setting in LTP will become accurate.  A lot of the current flight times in LTP do seem to be correct from testing though.

**Comment by leatrix** [comment]
Show flight times will get more updates in a couple of days (currently the updates are included in alpha releases).  I'm very happy with how that setting turned out in the latest alpha and the setting now includes a copy-friendly window to make it very easy for people to report incorrect or missing flight times too.  From what I can tell, LTP now includes more flight times than any other addon and if people use the easy-to-use report panel built into the addon then the setting can contain all flight times and they will all be accurate.

**Comment by SawyerMBlack** [comment]
Thanks for being a great dev!
