### ISSUE TITLE
Leatrix plus on Classic WoW Auto BG release bug

### ISSUE THREAD

**Issue by LordGerek** [leatrix/leatrix-plus-classic#32]
Hello I have an issue in BGs where the auto release will always happen regardless of it being checked or not. I have disabled LTP and it doesn't do this so I know it a bug in this add-on. I tried reinstalling it yet it still happens.

**Comment by leatrix** [comment]
That's confusing because for Classic Era/SoM, the very first line of the code that auto releases checks whether the checkbox is checked and only continues with the auto release if it is checked.

If it was only affecting one or two battlegrounds (as was the case with Shadowlands) then it could be an incorrect map ID but if it's affecting all battlegrounds then it can't be that.

I know that you disabled LTP but try it the other way around.  Disable all addons except LTP and see what happens.  You only need to do it for a couple of deaths then you can enable your other addons again.

**Comment by LordGerek** [comment]
Turns out I'm slightly dense and thought I combed through it all, somehow I missed dbm pvp has an auto release function. Sorry for this hehe
________________________________
