### ISSUE TITLE
Enhance quest log leads to quests not being clickable when linking them in chat

### ISSUE THREAD

**Issue by Trust-WoW** [leatrix/leatrix-plus-classic#9]
When enabling the LTP option "enhance quest log", quests that I post into chat via Shift+Click are not shown as links, but text only.

Questie is enabled and up-to-date, as is LTP.

When I disable the option "enhance quest log", the chat linking works fine and I and others can click the link and the quest tooltip opens. I can always click quest links that others have posted, regardless if the LTP option is on or off.

I tested this with friends, who run the same setup (Questie and LTP with the option enabled) and for them it works as intended.
One of the Questie developers has confirmed in Discord that it works for him as well. 

I have already tried deleting the .lua files for LTP while the game was closed to reset the options, however with no luck. Even with all other LTP options turned off and only "enhance quest log" enabled, it does not work.
This issue is not character specific, but happens on all my characters.

**Comment by leatrix** [comment]
Default Wow Classic does not show quest links in chat.  It only shows text.  Questie is showing the quest links in chat.  I tested LTP (with 'Enhance quest log' enabled) with Questie and quest links were shown in chat.  However, sometimes, the first quest that I got after logging in was not shown as a link (this only happened sometimes).  So when you test, test it with a few quests after logging in, not just one as the first time you shift-click a quest after logging in (or reloading), it might not be shown as a link in chat.

I tested Questie on its own and no other addons enabled and got the same result - after logging in or reloading, sometimes the first quest I shift-clicked was not shown as a link in chat but subsequent quests were (so far as I tested).  This minor issue is obviously caused by Questie since Questie is putting the links in chat in the first place.

So I don't think this is anything to do with LTP.  LTP doesn't interfere with the quest log or chat links at all.  All 'Enhance quest log' does is change the textures used to draw the quest log, add a map button and show quest levels.  However, Questie interferes with quite a lot of things including chat links.  So the problem is more likely to be with Questie or another addon you have installed.

When testing, ensure that there are no other addons enabled at all as other addons could prevent Questie from showing quest links in chat.  I don't think LTP is doing that though.

There's no need to logout and delete your LTP saved settings files.  Just run '/ltp wipe'.  It essentially does the same thing.

**Comment by Trust-WoW** [comment]
Thank you for testing!
I found the addon that is causing the issue: https://www.curseforge.com/wow/addons/ludwig
The problem with Ludwig is this: "Allows you to easily type any item [[link] into the chat."
Ludwig uses the same modifier to link to chat, which probably breaks the feature for Questie.

So, as you said, LTP has nothing to do with this.
